# Generated by Django 5.1.2 on 2024-12-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_post', '0003_alter_post_user'),
        ('credentials', '0005_user_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='credentials.user_table'),
        ),
    ]
