# Generated by Django 5.1.2 on 2024-12-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_application_user_delete_user_table'),
        ('employer', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
