# Generated by Django 5.1.2 on 2025-01-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
