# Generated by Django 5.1.2 on 2025-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
