# Generated by Django 5.1.2 on 2024-12-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hr',
        ),
        migrations.AddField(
            model_name='employer_table',
            name='company_exist',
            field=models.BooleanField(default=False),
        ),
    ]
