# Generated by Django 5.1.2 on 2024-12-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_company_hr_employer_table_company_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='employer.employer_table'),
        ),
    ]
