# Generated by Django 5.1.2 on 2024-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_company_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.IntegerField(default=1),
        ),
    ]
