# Generated by Django 5.1.2 on 2024-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_company_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
