# Generated by Django 5.1.2 on 2024-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_company_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_table',
            name='username',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
