# Generated by Django 5.1.2 on 2024-12-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_employer_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='employer.company'),
        ),
        migrations.CreateModel(
            name='req_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_skill', models.CharField(max_length=100)),
                ('skill_2', models.CharField(max_length=50)),
                ('skill_3', models.CharField(max_length=50)),
                ('skill_4', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('speak_lng_1', models.CharField(max_length=50)),
                ('speak_lng_2', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_skill', to='employer.job')),
            ],
        ),
    ]
