# Generated by Django 5.1.2 on 2025-01-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='hr',
            new_name='cmp_email',
        ),
    ]
