# Generated by Django 5.1.2 on 2025-01-05 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_rename_hr_company_cmp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_table',
            name='username',
        ),
        migrations.AlterField(
            model_name='employer_table',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be a 10-digit number.')]),
        ),
    ]
