# Generated by Django 5.1.2 on 2025-01-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_remove_employer_table_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='city',
        ),
    ]
