# Generated by Django 5.1.2 on 2025-01-11 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_rename_address_company_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_table',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be a 10-digit number.')]),
        ),
    ]
