# Generated by Django 5.1.2 on 2025-01-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_rename_bio_company_desctiption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='desctiption',
            new_name='description',
        ),
    ]
