# Generated by Django 5.1.2 on 2025-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_rename_desctiption_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='company_images/default.png', null=True, upload_to='company_images'),
        ),
    ]
