# Generated by Django 5.1.2 on 2025-01-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_vacancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_location',
            field=models.CharField(choices=[('WFH', 'Work from home'), ('WFO', 'Work from office'), ('WFH_WFO', 'Work from home and office')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('IN', 'Internship'), ('HR', 'Hourly')], max_length=100, null=True),
        ),
    ]
