# Generated by Django 5.1.2 on 2025-01-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_job_total_vacancy_job_working_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship'), ('Hourly', 'Hourly')], max_length=100, null=True),
        ),
    ]
