# Generated by Django 5.1.2 on 2025-01-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_alter_job_working_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1 year', '1 year'), ('1-3 years', '1-3 years'), ('3-6 years', '3-6 years'), ('6-10 years', '6-10 years'), ('10+ years', '10+ years')], max_length=100, null=True),
        ),
    ]
