# Generated by Django 5.1.2 on 2025-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0022_alter_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='working_location',
            new_name='work_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='company_images/default.png', null=True, upload_to='company_images'),
        ),
    ]
