# Generated by Django 5.1.2 on 2025-01-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0025_alter_job_work_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_maximum',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_minimum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
