# Generated by Django 5.1.2 on 2025-01-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0026_rename_salary_job_salary_maximum_job_salary_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_maximum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_minimum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
