# Generated by Django 5.1.2 on 2025-01-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0027_alter_job_salary_maximum_alter_job_salary_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timesince',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
