# Generated by Django 5.1.2 on 2025-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0028_job_timesince'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_disclose',
            field=models.BooleanField(null=True),
        ),
    ]
