# Generated by Django 5.1.2 on 2025-01-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0031_alter_job_salary_disclose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='timesince',
        ),
    ]
