# Generated by Django 5.1.2 on 2025-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0033_job_current_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='perks',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
