# Generated by Django 5.1.2 on 2024-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='username',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
