# Generated by Django 5.1.2 on 2024-12-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_user_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
