# Generated by Django 5.1.2 on 2024-12-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_user_table_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='username',
        ),
    ]
