# Generated by Django 5.1.2 on 2024-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_remove_user_table_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
