# Generated by Django 5.1.2 on 2025-01-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_alter_user_table_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='../media/logos/default_user.png', upload_to='user_profile_image'),
        ),
    ]
