# Generated by Django 5.1.2 on 2025-01-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0010_alter_user_table_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='logos/default_user.png', upload_to='user_profile_image'),
        ),
    ]
