# Generated by Django 5.1.2 on 2025-01-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0011_alter_user_table_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='complete_profile',
            field=models.BooleanField(default=False),
        ),
    ]
