# Generated by Django 5.1.2 on 2025-01-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0012_user_table_complete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='user_bio',
        ),
    ]
