# Generated by Django 5.1.2 on 2025-01-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0013_remove_user_table_age_remove_user_table_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.BooleanField(default=False)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('iti_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('postgraduate_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('current_working', models.BooleanField(default=False)),
                ('notice_period', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('work_end_date', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('english', models.BooleanField(default=False)),
                ('other_languages', models.TextField(blank=True, null=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('work_from_home', models.BooleanField(default=False)),
                ('work_from_office', models.BooleanField(default=False)),
                ('field_job', models.BooleanField(default=False)),
                ('full_time', models.BooleanField(default=False)),
                ('part_time', models.BooleanField(default=False)),
                ('hourly', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='credentials.user_table')),
            ],
        ),
    ]
