# Generated by Django 5.1.2 on 2025-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='selected_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
