# Generated by Django 5.1.2 on 2025-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
