# Generated by Django 5.1.2 on 2025-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0002_rename_selected_date_userdetail_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
