# Generated by Django 5.1.2 on 2025-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0003_userresume_created_at_userresume_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='applying_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
