# Generated by Django 5.1.2 on 2025-01-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0004_userdetail_applying_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='english_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
