# Generated by Django 5.1.2 on 2025-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0004_userresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='resume_file',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
