# Generated by Django 5.1.2 on 2025-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0006_remove_userdetail_english_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
