# Generated by Django 5.1.2 on 2025-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0007_alter_internship_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='work_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
