# Generated by Django 5.1.2 on 2025-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0008_alter_userdetail_work_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='experience',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='total_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
